name: build_and_run
on: [push]
jobs:
    build_and_run:
        runs-on: ubuntu-latest
        stages:
            uses: actions/checkout@v4
            run: g++ main.cpp my_add.cpp -o main
            run: ./main 4 6